apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-script
spec:
  steps:
   - name: step-with-script
     image: registry.access.redhat.com/ubi8/ubi-minimal
     script: |
       #!/usr/bin/env bash
       echo "Installing iputils"
       yum install iputils -y
       ping redhat.com -c 3
       echo "It worked!"
