apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: bitnami/mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: mysql-config-env-file
              key: MYSQL_ROOT_PASSWORD
      volumeMounts:
        - name: nfs-storage
          mountPath: /bitnami/mysql
    volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
