apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    type: mysql 
spec:
  selector:
    matchLabels:
      type: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
